### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by daniel-sungwon-lee** [daniel-sungwon-lee/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Listen for 'keydown' events on the document.
- [x] Create function that changes the orientation of car depending on the arrow keys pressed
- [x] Add transitions
- [x] Check for bugs

https://camo.githubusercontent.com/c3ab3155ae64109a6263bf907dcdc570ef9b9404e88728cea8f65f3faad9469a/68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d7475726e2d74686569722d6361722e676966
